-- 0001_baseline -- complete ZingLib 1.0 database schema.
--
-- DO NOT EDIT THIS FILE. It is recorded in schema_version by checksum; editing
-- it means the file and every existing database disagree about what v1 is. Add
-- a new numbered migration instead.
--
-- Not supported here: CREATE INDEX CONCURRENTLY and anything else that cannot
-- run inside a transaction -- each migration is applied in one.

-- LANraragi JSONL analysis schema (text-only, pgvector-ready)

-- pgvector
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS works (
    arcid         text PRIMARY KEY,
    title         text NOT NULL DEFAULT '',
    tags          text[] NOT NULL DEFAULT ARRAY[]::text[],

    -- VLM-generated description text
    description   text,

    -- Embeddings (pgvector)
    desc_embedding   vector(1024),
    visual_embedding vector(1152),
    page_visual_embedding vector(1152),
    cover_embedding_status text NOT NULL DEFAULT 'pending',

    -- Timestamp-like fields extracted from tags (epoch seconds)
    eh_posted     bigint,
    date_added    bigint,
    lastreadtime  bigint,

    -- Raw line from JSONL (for future reprocessing)
    raw           jsonb NOT NULL DEFAULT '{}'::jsonb,

    -- Runtime-local gallery location (relative to runtime/local_lib)
    local_dir     text NOT NULL DEFAULT '',

    -- Source marker: lrr/local/missing
    source        text NOT NULL DEFAULT 'lrr',

    last_seen_at  timestamptz NOT NULL DEFAULT now()
);

-- Backfill-friendly schema upgrades for existing installs
ALTER TABLE works ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE works ADD COLUMN IF NOT EXISTS desc_embedding vector(1024);
ALTER TABLE works ADD COLUMN IF NOT EXISTS visual_embedding vector(1152);
ALTER TABLE works ADD COLUMN IF NOT EXISTS page_visual_embedding vector(1152);
ALTER TABLE works ADD COLUMN IF NOT EXISTS cover_embedding_status text NOT NULL DEFAULT 'pending';
ALTER TABLE works ADD COLUMN IF NOT EXISTS local_dir text NOT NULL DEFAULT '';
ALTER TABLE works ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'lrr';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'works_source_chk'
    ) THEN
        ALTER TABLE works
        ADD CONSTRAINT works_source_chk
        CHECK (source IN ('lrr', 'local', 'missing', 'pending', 'processing'));
    END IF;
END $$;

UPDATE works
SET cover_embedding_status = CASE
    WHEN visual_embedding IS NOT NULL AND page_visual_embedding IS NOT NULL THEN 'complete'
    WHEN cover_embedding_status IN ('processing', 'fail') THEN cover_embedding_status
    ELSE 'pending'
END;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'works_cover_embedding_status_chk'
    ) THEN
        ALTER TABLE works
        ADD CONSTRAINT works_cover_embedding_status_chk
        CHECK (cover_embedding_status IN ('pending', 'processing', 'complete', 'fail'));
    END IF;
END $$;

-- Fast tag membership queries: WHERE tags @> ARRAY['artist:foo']
CREATE INDEX IF NOT EXISTS idx_works_tags_gin ON works USING gin (tags);
CREATE INDEX IF NOT EXISTS idx_works_lastreadtime ON works (lastreadtime);
CREATE INDEX IF NOT EXISTS idx_works_eh_posted ON works (eh_posted);
CREATE INDEX IF NOT EXISTS idx_works_date_added ON works (date_added);
CREATE INDEX IF NOT EXISTS idx_works_cover_status ON works (cover_embedding_status);
CREATE INDEX IF NOT EXISTS idx_works_source ON works (source);
CREATE INDEX IF NOT EXISTS idx_works_local_dir ON works (local_dir);

-- Vector search indexes (HNSW)
CREATE INDEX IF NOT EXISTS idx_works_desc_vec ON works USING hnsw (desc_embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_works_visual_vec ON works USING hnsw (visual_embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_works_page_visual_vec ON works USING hnsw (page_visual_embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS read_events (
    id           bigserial PRIMARY KEY,
    arcid        text NOT NULL REFERENCES works(arcid) ON DELETE CASCADE,
    read_time    bigint NOT NULL,
    source_file  text NOT NULL,
    ingested_at  timestamptz NOT NULL DEFAULT now(),
    raw          jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (arcid, read_time)
);

CREATE INDEX IF NOT EXISTS idx_read_events_read_time ON read_events (read_time);
CREATE INDEX IF NOT EXISTS idx_read_events_arcid ON read_events (arcid);



-- Runtime configuration store (PG -> JSON -> ENV fallback chain).
CREATE TABLE IF NOT EXISTS app_config (
    scope        text NOT NULL DEFAULT 'global',
    key          text NOT NULL,
    value        text NOT NULL,
    value_type   text NOT NULL DEFAULT 'string',
    is_secret    boolean NOT NULL DEFAULT false,
    description  text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (scope, key)
);

ALTER TABLE app_config ADD COLUMN IF NOT EXISTS scope text NOT NULL DEFAULT 'global';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS value text;
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS value_type text NOT NULL DEFAULT 'string';
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS is_secret boolean NOT NULL DEFAULT false;
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_app_config_updated_at ON app_config (updated_at);

-- User interactions for recommendation feedback (click/read/dislike).
CREATE TABLE IF NOT EXISTS user_interactions (
    id           bigserial PRIMARY KEY,
    user_id      text NOT NULL DEFAULT 'default_user',
    session_id   text,
    arcid        text NOT NULL,
    action_type  text NOT NULL,
    weight       double precision NOT NULL DEFAULT 1.0,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT user_interactions_action_type_chk CHECK (action_type IN ('click', 'read', 'dislike', 'impression'))
);

ALTER TABLE user_interactions ADD COLUMN IF NOT EXISTS user_id text NOT NULL DEFAULT 'default_user';
ALTER TABLE user_interactions ADD COLUMN IF NOT EXISTS session_id text;
ALTER TABLE user_interactions ADD COLUMN IF NOT EXISTS arcid text;
ALTER TABLE user_interactions ADD COLUMN IF NOT EXISTS action_type text;
ALTER TABLE user_interactions ADD COLUMN IF NOT EXISTS weight double precision NOT NULL DEFAULT 1.0;
ALTER TABLE user_interactions ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'user_interactions_action_type_chk'
    ) THEN
        ALTER TABLE user_interactions
        ADD CONSTRAINT user_interactions_action_type_chk
        CHECK (action_type IN ('click', 'read', 'dislike', 'impression'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_interactions_user_arcid ON user_interactions (user_id, arcid);
CREATE INDEX IF NOT EXISTS idx_user_interactions_user_action_created ON user_interactions (user_id, action_type, created_at);
CREATE INDEX IF NOT EXISTS idx_user_interactions_session_created ON user_interactions (session_id, created_at);

-- Cached user vector profile for fast Rocchio-style recommend retrieval.
CREATE TABLE IF NOT EXISTS user_profiles (
    user_id      text PRIMARY KEY,
    session_id   text,
    base_vector  vector(1024),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS session_id text;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS base_vector vector(1024);
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_user_profiles_updated_at ON user_profiles (updated_at);

-- Web UI accounts and sessions.
CREATE TABLE IF NOT EXISTS ui_users (
    uid           uuid PRIMARY KEY,
    username      text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    role          text NOT NULL DEFAULT 'admin',
    created_at    timestamptz NOT NULL DEFAULT now(),
    disabled      boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS ui_sessions (
    sid          uuid PRIMARY KEY,
    uid          uuid NOT NULL REFERENCES ui_users(uid) ON DELETE CASCADE,
    token_hash   text NOT NULL UNIQUE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    ip           text NOT NULL DEFAULT '',
    user_agent   text NOT NULL DEFAULT '',
    revoked      boolean NOT NULL DEFAULT false,
    csrf_hash    text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ui_meta (
    key        text PRIMARY KEY,
    value      text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ui_sessions_uid ON ui_sessions (uid);
CREATE INDEX IF NOT EXISTS idx_ui_sessions_expires_at ON ui_sessions (expires_at);
